### ISSUE TITLE
Branch

### ISSUE THREAD

**Issue by 23350406** [23350406/Python#14]
Задача сделать игру "Кроссплатформенной".  Для этого создай отдельную ветку с названием python_for_windows и всю разработку проводи в данной ветке. Она будет как вторая ветка main, поэтому выполняя любую подзадачу, необходимо создавать от неё дополнительные ветки. 

В главной ветке main теперь необходимо вести разработку исключительно под unix системы. Рефактором под unix системы будет заниматься @23350406. Поэтому @frozzzen123, тебе нужно проводить разработку исключительно под Windows. Всем остальным займутся дети терминала...

**Comment by frozzzen123** [comment]
Создал ветку
