### ISSUE TITLE
Разработка макета визуальной части процесса игры и части главного меню.

### ISSUE THREAD

**Issue by 23350406** [23350406/Python#4]
Необходимо разработать подробный макет (в любом из доступных средств визуализации макетов) основного экрана игры. На экране должны быть:

1. имя игрока, выделенное выбранным цветом,
2. очки за съеденное;
3. счёт игры (если это многораундовая игра)

**Comment by frozzzen123** [comment]
Сделал первый пункт

**Comment by frozzzen123** [comment]
Исправил недочеты

**Comment by frozzzen123** [comment]
Реализовал пункты 1.2 1.3 1.4
