### ISSUE TITLE
Разработка основного меню игры

### ISSUE THREAD

**Issue by 23350406** [23350406/Python#8]
Необходимо разработать основное меню игры с кнопками: Начать, Настройки и Выход с указанным ранее функционалом.

Для работы с настройками и их хранением в файле реализовать отдельный класс/модель для удобства работы.

**Comment by frozzzen123** [comment]
Создал начальную визуализацию меню в состоянии по default. Т.е. создано отображение меню без какого-либо взаимодействия с пользователем. В конце разработки проекта картинки будут переработаны (улучшен дизайн). Предложения по стилизации приветствуются

**Comment by frozzzen123** [comment]
1. Создал функцию и картинки для меню начала игры.
2. Codestyle
3. Создан переход между основным меню и меню начала игры.

**Comment by frozzzen123** [comment]
Реализовал счетчики количества раундов и ботов
Переработал нажатие кнопки

**Comment by frozzzen123** [comment]
Переработал систему файлов с кодом

**Comment by frozzzen123** [comment]
Добавлен выбор и вывод размера карты на экран

**Comment by 23350406** [comment]
нааайс
